import os
from collections import defaultdict

import matplotlib as mpl
import numpy as np
import pandas as pd
import seaborn as sb
from matplotlib import pyplot as plt

# for visual settings and compatibility with adobe illustrator
import plot_params
from general_params_glycFDR import out

cm = 1 / 2.54  # centimeters in inches

df_bindings = pd.read_csv(os.path.join(
    out, 'tables/binding_predictions_best-allele.tsv'),
                          sep='\t',
                          header=0)

alleles = pd.read_csv(os.path.join(out, 'tables/bindings_alleles.tsv'),
                      sep='\t',
                      header=0)
complete_annotation_subject = alleles[
    alleles['Alleles annotation notes'].isnull()].Subject.tolist()
df_bindings = df_bindings[df_bindings['Binding Type'] == 'Non-trash']

df_bindings = df_bindings[df_bindings['Subject'].isin(
    complete_annotation_subject)]

# generated by './figure_2_glycosites.py'
glyco_path = os.path.join(out, 'tables/glycosites.tsv')

# reading tables for all studies
psm_glyco = pd.read_csv(glyco_path, sep='\t', header=0, low_memory=False)
psm_glyco['Glycosylated'] = True

# fetching glycan type annotation
glyc_ann_path = os.path.join(out, 'tables/NGlycans_groups.tsv')

df_glycan_annotation = pd.read_csv(glyc_ann_path,
                                   sep='\t',
                                   header=0,
                                   comment='#')
df_glycan_annotation.columns = [
    'Mass', 'Observed Modifications', 'Glycan Type'
]
df_glycan_annotation['Observed Modifications'] = df_glycan_annotation[
    'Observed Modifications'].str.replace(' %.+$', '', regex=True)

converter = {
    'O-Mannose': "Other",
    'O-glycan': "Other",
    "Truncated": "Truncated",
    "High Mannose": "High Mannose",
    "High Mannose w/Fucose": "High Mannose",
    "Complex/Hybrid w/Fucose & NeuAc": "Complex/Hybrid",
    "Truncated w/Fucose": "Truncated",
    "Truncated Complex/Hybrid": "Truncated Complex/Hybrid",
    "Truncated Complex/Hybrid w/Fucose": "Truncated Complex/Hybrid",
    "Complex/Hybrid": "Complex/Hybrid",
    "Complex/Hybrid w/Fucose": "Complex/Hybrid",
    "Complex/Hybrid w/NeuAc": "Complex/Hybrid"
}
df_glycan_annotation['Glycan Type'] = df_glycan_annotation['Glycan Type'].map(
    converter)
psm_glyco['Observed Modifications'] = psm_glyco[
    'Observed Modifications'].str.replace(' %.+$', '', regex=True)
psm_glyco = psm_glyco.merge(df_glycan_annotation, how='left')

# processing tabels and merging
df_bindings = df_bindings.merge(psm_glyco[[
    'Peptide', 'Subject', 'Glyco Position', 'Glycosylated', 'Glycan Type',
    'Mass', 'Glyco site'
]].drop_duplicates(),
                                how='left')
df_bindings['Glycosylated'] = df_bindings['Glycosylated'].fillna(False)

df_glyco = df_bindings[df_bindings['Glycosylated']].copy(deep=True)
df_glyco['Core start'] = df_glyco.apply(lambda x: x.Peptide.index(x.Core),
                                        axis=1) + 1
df_glyco['Glyco position within motif'] = df_glyco[
    'Glyco Position'] - df_glyco['Core start']
df_glyco['HLA Group'] = df_glyco['NetMHCIIpan Allele'].str.extract(
    '(D[P|Q|R])')[0]
# add inside vs outside motif column
df_glyco['Glycosylation Location Type'] = (
    df_glyco['Glyco position within motif'] >=
    0) & (df_glyco['Glyco position within motif'] <= 8)
df_glyco['Glycosylation Location Type'] = df_glyco[
    'Glycosylation Location Type'].map({
        True: 'Within HLA motif',
        False: 'Outside HLA motif'
    })
# Check glycoyslation position (inside / outside HLA motif) per HLA group
# Groups: DP, DQ, DR

df_plot_1 = df_glyco.groupby('HLA Group').apply(lambda x: x[
    'Glycosylation Location Type'].value_counts(normalize=True)).unstack(
        level=1)

df_plot_1 = round(df_plot_1, 4) * 100
cols_order = ["Within HLA motif", 'Outside HLA motif']

fig, axes = plt.subplots(1,
                         2,
                         figsize=(7, 4),
                         gridspec_kw={'width_ratios': [1, 10]},
                         constrained_layout=True)
axes = axes.flatten()

ax = axes[0]
df_plot_1[cols_order].plot(kind='bar',
                           ax=ax,
                           stacked=True,
                           color=['red', 'gray'])
ax.set_ylabel('Glyco peptides (%)')
ax.set_xlabel('HLA group')

ax = axes[1]
df_plot_2 = df_glyco.groupby('Glyco position within motif').agg({
    'Mass': 'mean'
}).unstack(level=1)
df_plot_2.plot(kind='bar', ax=ax)
ax.set_ylabel('Average glycan mass (Da)')
ax.set_xlabel('HLA group')

plt.savefig(os.path.join(
    out, 'plots/figure_2/panel_relativePositionPerHlaGroup.pdf'),
            transparent=True)


# Check glycan types per HLA group
df_plot_5 = round(
    df_glyco.groupby('HLA Group').apply(lambda x: x[
        'Glycan Type'].value_counts(normalize=True)).unstack(level=1), 4) * 100
cols_order = [
    "Truncated", "High Mannose", "Truncated Complex/Hybrid", "Complex/Hybrid",
    "Other"
]
fig, ax = plt.subplots(1,
                       1,
                       figsize=(3 * cm, 5.8 * cm),
                       constrained_layout=True)
colors = ["#e63946", "#f1faee", "#a8dadc", "#457b9d", "#1d3557"]
ax.set_ylabel('Glycan type (%)')
df_plot_5[cols_order].plot(kind='bar',
                           ax=ax,
                           stacked=True,
                           legend=True,
                           color=colors,
                           align='center')
plt.savefig(os.path.join(out, 'plots/figure_2/panel_glycanTypes.pdf'),
            transparent=True)

